#Distinct powers Q29
#How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

terms = []

for n in range(2,101):
    for p in range(2,101):
        term = n ** p
        if term not in terms:
            terms.append(term)

terms.sort()
print("The count of distinct terms is {}".format(len(terms)))