#The sequence of triangle numbers is generated by adding the natural numbers.
#What is the value of the first triangle number to have over five hundred divisors?
def listFactors(num):
    factors = 0
    for n in range(1,num+1):
        if num % n == 0:
            factors += 1

    return factors


number = 0
for n in range(1,100000000):
    number += n
    a = listFactors(number)
    print("{} {}".format(number, a))
    if a > 500:
        print("Num {} {}".format(number,a))
        break